# Default values for genomicsdb.
# This is a YAML-formatted file.
replicaCount: 1

storage:
    size: 250Gi

# credentials that have enough privileges to restore a database
adminuser: ""
adminpassword: ""

# when populated, this will download the backup file (placed in /projects/stars/var/data_services) and initiate the restore
dataUrl: "" # https://stars.renci.org/var/data_services/genomics/k8s_pg_backup.zip

# DB startup credentials
user: postgres
password: ""
dbName: ""
zipPassword" "zRmkCwyQKuvEFYVW0ylf"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5432

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ""
  tls: []

resources:
  requests:
    memory: 16Gi
    cpu: 1000m
  limits:
    memory: 32Gi
    cpu: 2000m