# Default values for genomicsdb.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: bitnami/postgresql
  tag: 14.2.0
  pullPolicy: IfNotPresent

# if migrating, this should have host and database fields
dbMigration: {}

storage:
    size: 25Gi

shmSize: ""

adminuser: changeme
adminpassword: "changeme"
dataUrl: ""
zipPassword: ""
zipFileName: ""
sqlFile1: ""
sqlFile2: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

# formatted as text string like in postgresql.conf (e.g., `max_wal_size = 1GB`)
extendedPostgresOptions: ""

service:
  type: ClusterIP
  port: 5432

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ""
  tls: []

resources:
  requests:
    memory: 8Gi
    cpu: 1000m
  limits:
    memory: 16Gi
    cpu: 2000m

initresources:
  limits:
    memory: 10Gi
    cpu: 2000m

nodeSelector: {}

tolerations: []

affinity: {}
