# Default values for genomicsdb.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: postgres
  tag: latest
  pullPolicy: IfNotPresent

storage:
    size: 25Gi

adminuser: changeme
adminpassword: "changeme"
dataUrl: ""
zipPassword: ""
zipFileName: ""
sqlFile1: ""
sqlFile2: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5432

networking:
  enabled: false
  type: "sometype"
  loadbalancerIP:
  name: "somename"
  port: 1234
  protocol: "someprotocol"
  host: "somehost"

resources:
  requests:
    memory: 8Gi
    cpu: 1000m
  limits:
    memory: 16Gi
    cpu: 2000m

initresources:
  limits:
    memory: 10Gi
    cpu: 2000m

nodeSelector: {}

tolerations: []

affinity: {}
