# Default values for genomicsdb.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: bitnami/postgresql
  tag: 15.2.0
  pullPolicy: IfNotPresent

# if migrating, this should have host and database fields
dbMigration: {}

dbStorageSize: 25Gi # may very well want more...

#backupStorageSize: 10Gi # can be smaller than the db, since indexes are not stored, but depends on how many you keep...

shmSize: ""

adminuser: changeme
adminpassword: "changeme"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  runAsUser: 1001

# formatted as text string like in postgresql.conf (e.g., `max_wal_size = 1GB`)
extendedPostgresOptions: ""

service:
  type: ClusterIP
  port: 5432

networking:
  enabled: false
  type: "sometype"
  loadbalancerIP:
  name: "somename"
  port: 1234
  protocol: "someprotocol"
  host: "somehost"

resources:
  requests:
    memory: 8Gi
    cpu: 1000m
  limits:
    memory: 16Gi
    cpu: 2000m

initresources:
  limits:
    memory: 10Gi
    cpu: 2000m

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 90
  periodSeconds: 60
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
