apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "genomicsdb.fullname" . }}-backup-pvc"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.loadStorage.size }}