{{ if .Values.backupStorageSize }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "genomicsdb.fullname" . }}-backup"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backupStorageSize }}
{{ end }}
