apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "genomicsdb.fullname" . }}-password"
  labels:
    {{- include "genomicsdb.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.adminpassword | quote }}