apiVersion: v1
kind: Service
metadata:
  name: {{ include "genomicsdb.fullname" . }}
  labels:
  {{- include "genomicsdb.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.networking.host }}
spec:
  type: {{ .Values.networking.type }}
  loadBalancerIP: {{ .Values.networking.loadbalancerIP }}
  ports:
  - name: {{ .Values.networking.name }}
    port: {{ .Values.networking.port }}
    protocol: TCP
  selector:
    {{- include "genomicsdb.selectorLabels" . | nindent 4 }}

{{ if .Values.networking.enabled }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-loadbalancer-ports
spec:
  podSelector:
    matchLabels:
      type: dbms
  ingress:
  - from: []
    ports:
      - port: {{ .Values.service.port }}
{{ end }}